#!/usr/bin/env node
/**
 * README generator for After Effects Scripts.
 *
 * Reads script metadata directly from the repo and generates a catalog-style
 * README.md grouped by category.
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { ROOT, collectCatalogScripts } from './lib/catalog.mjs';

const README_PATH = join(ROOT, 'README.md');

const CATEGORY_ORDER = [
  'App',
  'Project',
  'Comp',
  'Layer',
  'Effect',
  'Keyframe',
  'Expression',
];

const STATIC_HEADER = [
  '# After Effects Scripts',
  '',
  'A collection of After Effects utilities for KBar, Tool Launcher, Quick Menu, or any other script file launcher.',
  '',
  'These tools were developed mainly for my own personal workflow and may not have been tested very thoroughly. As After Effects evolves, some scripts may stop working or need maintenance. Run them at your own discretion.',
  '',
  '## Installation Instructions',
  '',
  '1. Open the script you want from the catalog below.',
  '2. Download the corresponding `.jsx` file.',
  '3. In After Effects, go to `File > Scripts > Run Script File...` and choose the downloaded script.',
  '',
];

function escapeCell(value) {
  return String(value ?? '')
    .replace(/\|/g, '\\|')
    .replace(/\r?\n/g, ' ')
    .trim();
}

function buildModifierTable(script) {
  const modifiers = [
    script.shiftClick ? ['Shift-click', script.shiftClick] : null,
    script.cmdClick ? ['Cmd-click', script.cmdClick] : null,
    script.altClick ? ['Alt-click', script.altClick] : null,
  ].filter(Boolean);

  if (modifiers.length === 0) return [];

  return [
    '',
    '| Modifier | Action |',
    '| --- | --- |',
    ...modifiers.map(([name, value]) => `| ${name} | ${escapeCell(value)} |`),
  ];
}

function buildScriptBlock(script) {
  const icon = script.icon
    ? `<img src="${script.icon}" alt="${escapeCell(script.name)} icon" width="20" height="20">`
    : (script.iconText ? `\`${escapeCell(script.iconText)}\`` : '');

  const title = icon ? `### ${icon} ${escapeCell(script.name)}` : `### ${escapeCell(script.name)}`;

  return [
    title,
    '',
    escapeCell(script.description),
    ...buildModifierTable(script),
    '',
  ].join('\n');
}

function buildCategorySection(category, scripts) {
  return [
    `## ${category}`,
    '',
    ...scripts.map(buildScriptBlock),
  ].join('\n');
}

function main() {
  const scripts = collectCatalogScripts(ROOT);

  const categories = new Map();
  for (const script of scripts) {
    const key = script.category || 'Uncategorized';
    if (!categories.has(key)) categories.set(key, []);
    categories.get(key).push(script);
  }

  const orderedCategories = [
    ...CATEGORY_ORDER.filter(category => categories.has(category)),
    ...[...categories.keys()].filter(category => !CATEGORY_ORDER.includes(category)),
  ];

  const lines = [
    ...STATIC_HEADER,
    '## Categories',
    '',
    ...orderedCategories.map(category => `- ${category}: ${categories.get(category).length}`),
    '',
    ...orderedCategories.map(category => buildCategorySection(category, categories.get(category))),
    '_This README is auto-generated by `.github/scripts/generate-readme.mjs`._',
    '',
  ];

  writeFileSync(README_PATH, lines.join('\n'));
  process.stdout.write(`Generated README.md with ${scripts.length} scripts.\n`);
}

main();
